import { combineReducers } from 'redux';
import user from './user';
import session from './session';
import classInfo from './classInfo';
import badges from './badges';
import selectSession from './selectSession';
import dashboard from './dashboard';

const appReducer = combineReducers({
  user,
  session,
  classInfo,
  badges,
  selectSession,
  dashboard,
});

const rootReducer = (state, action) => {
  if (action.type === 'LOG_OUT') {
    state = undefined;
  }

  return appReducer(state, action);
};

export default rootReducer;

// The reducer generated by combineReducers({ a, b }) looks like this:

// // const combined = combineReducers({ a, b })
// function combined(state = {}, action) {
//   return {
//     a: a(state.a, action),
//     b: b(state.b, action)
//   };
// }
